#
# General test configuration
#
config:
  repeat: 5
  title: "Tests for the metrics extraction"

define:
  marathon_repo_dir: /Users/icharala/Develop/marathon

#
# Import everything
#
include:

  # We are going to run scale tests with one app with n number of instances
  - tests/1-app-n-instances-seq.yml

  # We are running marathon locally, so we are using the respective channels
  - lib/marathon-config-local-sim.yml

  # The simulation is targeting marathon, so include the marathon observers
  - lib/marathon-observers.yml

  # Measure deployment time and http-requests
  - measure/deployment-time.yml
  - measure/http-request-time.yml
  - measure/marathon-memory.yml
  - measure/marathon-threads.yml

  # We will dump the raw results, csv files and the image plots
  - reports/raw.yml
  - reports/csv.yml
  - reports/plots.yml
